function MissionSetup()
  PlayerSetControl(0)
  AreaTransitionXYZ(0, 270, -110, 6.4)
  Wait(200)
  AreaTransitionXYZ(14, -502.2488, 318.8277, 31.4111)
  PlayerSetControl(1)
  DisablePunishmentSystem(true)
  SoundPlayInteractiveStream("MS_BikeFunLow.rsm", 0.5)
  SoundSetMidIntensityStream("MS_BikeFunMid.rsm", 0.6)
  SoundSetHighIntensityStream("MS_BikeFunHigh.rsm", 0.6)
  SoundDisableSpeech_ActionTree()
  PedSetUniqueModelStatus(30, -1)
  PedSetUniqueModelStatus(31, -1)
  PedSetUniqueModelStatus(32, -1)
  PedSetUniqueModelStatus(33, -1)
  PedSetUniqueModelStatus(34, -1)
  PedSetUniqueModelStatus(35, -1)
  PedSetUniqueModelStatus(36, -1)
  PedSetUniqueModelStatus(37, -1)
  PedSetUniqueModelStatus(38, -1)
  PedSetUniqueModelStatus(146, -1)
  PedSetUniqueModelStatus(145, -1)
  PedSetUniqueModelStatus(85, -1)
  PedSetUniqueModelStatus(99, -1)
  PedSetUniqueModelStatus(147, -1)
  PedSetUniqueModelStatus(102, -1)
  PedSetUniqueModelStatus(134, -1)
  PedSetUniqueModelStatus(39, -1)
  PedSetUniqueModelStatus(75, -1)
  LoadAnimationGroup("1_02BYourSchool")
  LoadAnimationGroup("1_02_MeetWithGary")
  LoadAnimationGroup("1_03The Setup")
  LoadAnimationGroup("1_04TheSlingshot")
  LoadAnimationGroup("1_06ALittleHelp")
  LoadAnimationGroup("1_07_SaveBucky")
  LoadAnimationGroup("1_07_Sk8Board")
  LoadAnimationGroup("1_08ThatBitch")
  LoadAnimationGroup("1_08_MandPuke")
  LoadAnimationGroup("1_09_Candidate")
  LoadAnimationGroup("1_10Betrayal")
  LoadAnimationGroup("1_11B_HeBigPrank")
  LoadAnimationGroup("1_G1_TheDiary")
  LoadAnimationGroup("1_S01HatVsGall")
  LoadAnimationGroup("2_01LastMinuteShop")
  LoadAnimationGroup("2_02ComicKlepto")
  LoadAnimationGroup("2_05TadsHouse")
  LoadAnimationGroup("2_06MovieTickets")
  LoadAnimationGroup("2_07BeachRumble")
  LoadAnimationGroup("2_08WeedKiller")
  LoadAnimationGroup("2_4RichAreaRace")
  LoadAnimationGroup("2_G2CarnivalDate")
  LoadAnimationGroup("2_G2_GiftExchange")
  LoadAnimationGroup("2_R03PaperRoute")
  LoadAnimationGroup("2_S02CharSheets")
  LoadAnimationGroup("2_S04CharSheets")
  LoadAnimationGroup("2_S05_CooksCrush")
  LoadAnimationGroup("2_S06PantyRaid")
  LoadAnimationGroup("3_01JealousJohnny")
  LoadAnimationGroup("3_04WrongPtTown")
  LoadAnimationGroup("3_05TheTenements")
  LoadAnimationGroup("3_BFightJohnnyV")
  LoadAnimationGroup("3_G3")
  LoadAnimationGroup("3_R05ChemicalDeliv")
  LoadAnimationGroup("3_R08RaceLeague")
  LoadAnimationGroup("3_S03CheatinTime")
  LoadAnimationGroup("4_01Paparazzi")
  LoadAnimationGroup("4_04_FunhouseFun")
  LoadAnimationGroup("4_06BigGame")
  LoadAnimationGroup("4_B2_JockBossBattle")
  LoadAnimationGroup("5_01Grp")
  LoadAnimationGroup("5_01Rats")
  LoadAnimationGroup("5_02PrVandalized")
  LoadAnimationGroup("5_05Zoe")
  LoadAnimationGroup("5_09MakingAMark")
  LoadAnimationGroup("6B_PARA")
  LoadAnimationGroup("AGymLght")
  LoadAnimationGroup("Ambient")
  LoadAnimationGroup("Ambient2")
  LoadAnimationGroup("Ambient3")
  LoadAnimationGroup("ANIBBALL")
  LoadAnimationGroup("AniBroom")
  LoadAnimationGroup("AniDice")
  LoadAnimationGroup("AniFooty")
  LoadAnimationGroup("AniGlobe")
  LoadAnimationGroup("AnimSave")
  LoadAnimationGroup("AniPillo")
  LoadAnimationGroup("ARC3D")
  LoadAnimationGroup("Area_Asylum")
  LoadAnimationGroup("Area_Funhouse")
  LoadAnimationGroup("Area_GirlsDorm")
  LoadAnimationGroup("Area_Infirmary")
  LoadAnimationGroup("Area_School")
  LoadAnimationGroup("Area_Tenements")
  LoadAnimationGroup("Armor")
  LoadAnimationGroup("AsyBars")
  LoadAnimationGroup("AsyDoorB")
  LoadAnimationGroup("AsyDoors")
  LoadAnimationGroup("AsyGate")
  LoadAnimationGroup("AsyLever")
  LoadAnimationGroup("AsySwtch")
  LoadAnimationGroup("AtcPlank")
  LoadAnimationGroup("Authority")
  LoadAnimationGroup("BANANA")
  LoadAnimationGroup("barelLad")
  LoadAnimationGroup("BarrGate")
  LoadAnimationGroup("BATON")
  LoadAnimationGroup("BBALL_21")
  LoadAnimationGroup("bbgun")
  LoadAnimationGroup("BCatcher")
  LoadAnimationGroup("BdrDoorL")
  LoadAnimationGroup("BeardLady")
  LoadAnimationGroup("Bike")
  LoadAnimationGroup("BikeGar")
  LoadAnimationGroup("BoldRoll")
  LoadAnimationGroup("BoltCutt")
  LoadAnimationGroup("Boxing")
  LoadAnimationGroup("BoxRopes")
  LoadAnimationGroup("BRDoor")
  LoadAnimationGroup("BrkSwtch")
  LoadAnimationGroup("BROCKETL")
  LoadAnimationGroup("BRSwitch")
  LoadAnimationGroup("BusDoors")
  LoadAnimationGroup("Butcher")
  LoadAnimationGroup("BXPBag")
  LoadAnimationGroup("B_Striker")
  LoadAnimationGroup("CarnCurt")
  LoadAnimationGroup("CARNI01")
  LoadAnimationGroup("carnies")
  LoadAnimationGroup("Car_Ham")
  LoadAnimationGroup("Cavalier")
  LoadAnimationGroup("Cheer_Cool1")
  LoadAnimationGroup("Cheer_Cool2")
  LoadAnimationGroup("Cheer_Cool3")
  LoadAnimationGroup("Cheer_Gen1")
  LoadAnimationGroup("Cheer_Gen2")
  LoadAnimationGroup("Cheer_Gen3")
  LoadAnimationGroup("Cheer_Girl1")
  LoadAnimationGroup("Cheer_Girl2")
  LoadAnimationGroup("Cheer_Girl3")
  LoadAnimationGroup("Cheer_Girl4")
  LoadAnimationGroup("Cheer_Nerd1")
  LoadAnimationGroup("Cheer_Nerd2")
  LoadAnimationGroup("Cheer_Nerd3")
  LoadAnimationGroup("Cheer_Posh1")
  LoadAnimationGroup("Cheer_Posh2")
  LoadAnimationGroup("Cheer_Posh3")
  LoadAnimationGroup("Chem_Set")
  LoadAnimationGroup("ChLead_Idle")
  LoadAnimationGroup("CLadderA")
  LoadAnimationGroup("CnGate")
  LoadAnimationGroup("Coaster")
  LoadAnimationGroup("COPBIKE")
  LoadAnimationGroup("Cop_Frisk")
  LoadAnimationGroup("CV_Female")
  LoadAnimationGroup("CV_Male")
  LoadAnimationGroup("C_Wrestling")
  LoadAnimationGroup("DartBrd")
  LoadAnimationGroup("DartCab")
  LoadAnimationGroup("DodgeBall")
  LoadAnimationGroup("DodgeBall2")
  LoadAnimationGroup("DoorStr1")
  LoadAnimationGroup("DO_Edgar")
  LoadAnimationGroup("DO_Grap")
  LoadAnimationGroup("DO_StrikeCombo")
  LoadAnimationGroup("DO_Striker")
  LoadAnimationGroup("DRBrace")
  LoadAnimationGroup("Drumming")
  LoadAnimationGroup("DuffBag")
  LoadAnimationGroup("DunkBttn")
  LoadAnimationGroup("DunkSeat")
  LoadAnimationGroup("Earnest")
  LoadAnimationGroup("EnglishClass")
  LoadAnimationGroup("ErrandCrab")
  LoadAnimationGroup("Errand_BUS")
  LoadAnimationGroup("Errand_IND")
  LoadAnimationGroup("Errand_RIC")
  LoadAnimationGroup("Errand_SCH")
  LoadAnimationGroup("ESCDoorL")
  LoadAnimationGroup("ESCDoorR")
  LoadAnimationGroup("ExtWind")
  LoadAnimationGroup("FDoor")
  LoadAnimationGroup("FDoorB")
  LoadAnimationGroup("FDoorC")
  LoadAnimationGroup("Ferris")
  LoadAnimationGroup("FGhost")
  LoadAnimationGroup("FGoblin")
  LoadAnimationGroup("FlagA")
  LoadAnimationGroup("FLbBook")
  LoadAnimationGroup("FlbLader")
  LoadAnimationGroup("FLbPaint")
  LoadAnimationGroup("FLbTable")
  LoadAnimationGroup("FMCntrl")
  LoadAnimationGroup("FMDoor")
  LoadAnimationGroup("FMTrapDr")
  LoadAnimationGroup("FMTrapSw")
  LoadAnimationGroup("FortTell")
  LoadAnimationGroup("funCart")
  LoadAnimationGroup("funCurtn")
  LoadAnimationGroup("funMiner")
  LoadAnimationGroup("funRocks")
  LoadAnimationGroup("FunTeeth")
  LoadAnimationGroup("FXTestG")
  LoadAnimationGroup("F_Adult")
  LoadAnimationGroup("F_BULLY")
  LoadAnimationGroup("F_Crazy")
  LoadAnimationGroup("F_Douts")
  LoadAnimationGroup("F_Girls")
  LoadAnimationGroup("F_Greas")
  LoadAnimationGroup("F_Jocks")
  LoadAnimationGroup("F_Nerds")
  LoadAnimationGroup("F_OldPeds")
  LoadAnimationGroup("F_Pref")
  LoadAnimationGroup("F_Preps")
  LoadAnimationGroup("GarbCanA")
  LoadAnimationGroup("GatCool")
  LoadAnimationGroup("GEN_SOCIAL")
  LoadAnimationGroup("Gfight")
  LoadAnimationGroup("GhostDrs")
  LoadAnimationGroup("Gift")
  LoadAnimationGroup("Go_Cart")
  LoadAnimationGroup("Grap")
  LoadAnimationGroup("GymHoop")
  LoadAnimationGroup("GymWLad")
  LoadAnimationGroup("G_Grappler")
  LoadAnimationGroup("G_Johnny")
  LoadAnimationGroup("G_Striker")
  LoadAnimationGroup("Halloween")
  LoadAnimationGroup("HallWind")
  LoadAnimationGroup("Hang_Jock")
  LoadAnimationGroup("Hang_Moshing")
  LoadAnimationGroup("Hang_Talking")
  LoadAnimationGroup("Hang_Workout")
  LoadAnimationGroup("Hobos")
  LoadAnimationGroup("Hobo_Cheer")
  LoadAnimationGroup("HSdinger")
  LoadAnimationGroup("HUMIL_4-10_B")
  LoadAnimationGroup("HUMIL_4-10_C")
  LoadAnimationGroup("HUMIL_5-8F_A")
  LoadAnimationGroup("HUMIL_5-8F_B")
  LoadAnimationGroup("HUMIL_5-8V4-10")
  LoadAnimationGroup("HUMIL_5-8V6-1")
  LoadAnimationGroup("HUMIL_5-8VPLY")
  LoadAnimationGroup("HUMIL_5-8_A")
  LoadAnimationGroup("HUMIL_5-8_B")
  LoadAnimationGroup("HUMIL_5-8_C")
  LoadAnimationGroup("HUMIL_6-1V4-10")
  LoadAnimationGroup("HUMIL_6-1V6-1")
  LoadAnimationGroup("HUMIL_6-1VPLY")
  LoadAnimationGroup("HUMIL_6-1_A")
  LoadAnimationGroup("HUMIL_6-1_B")
  LoadAnimationGroup("HUMIL_6-1_C")
  LoadAnimationGroup("HUMIL_6-5V4-10")
  LoadAnimationGroup("HUMIL_6-5V6-1")
  LoadAnimationGroup("HUMIL_6-5VPLY")
  LoadAnimationGroup("HUMIL_6-5_A")
  LoadAnimationGroup("HUMIL_6-5_B")
  LoadAnimationGroup("HUMIL_6-5_C")
  LoadAnimationGroup("IDLE_AUTH_A")
  LoadAnimationGroup("IDLE_AUTH_B")
  LoadAnimationGroup("IDLE_AUTH_C")
  LoadAnimationGroup("IDLE_AUTH_D")
  LoadAnimationGroup("IDLE_BULLY_A")
  LoadAnimationGroup("IDLE_BULLY_B")
  LoadAnimationGroup("IDLE_BULLY_C")
  LoadAnimationGroup("IDLE_BULLY_D")
  LoadAnimationGroup("IDLE_CIVF_A")
  LoadAnimationGroup("IDLE_CIVF_B")
  LoadAnimationGroup("IDLE_CIVF_C")
  LoadAnimationGroup("IDLE_CIVM_A")
  LoadAnimationGroup("IDLE_CIVM_B")
  LoadAnimationGroup("IDLE_CIVM_C")
  LoadAnimationGroup("IDLE_DOUT_A")
  LoadAnimationGroup("IDLE_DOUT_B")
  LoadAnimationGroup("IDLE_DOUT_C")
  LoadAnimationGroup("IDLE_DOUT_D")
  LoadAnimationGroup("IDLE_FATG_A")
  LoadAnimationGroup("IDLE_FATG_B")
  LoadAnimationGroup("IDLE_FATG_C")
  LoadAnimationGroup("IDLE_FAT_A")
  LoadAnimationGroup("IDLE_FAT_B")
  LoadAnimationGroup("IDLE_FAT_C")
  LoadAnimationGroup("IDLE_GREAS_A")
  LoadAnimationGroup("IDLE_GREAS_B")
  LoadAnimationGroup("IDLE_GREAS_C")
  LoadAnimationGroup("IDLE_GREAS_D")
  LoadAnimationGroup("IDLE_GSF_A")
  LoadAnimationGroup("IDLE_GSF_B")
  LoadAnimationGroup("IDLE_GSF_C")
  LoadAnimationGroup("IDLE_GSM_A")
  LoadAnimationGroup("IDLE_GSM_B")
  LoadAnimationGroup("IDLE_GSM_C")
  LoadAnimationGroup("IDLE_JOCK_A")
  LoadAnimationGroup("IDLE_JOCK_B")
  LoadAnimationGroup("IDLE_JOCK_C")
  LoadAnimationGroup("IDLE_JOCK_D")
  LoadAnimationGroup("IDLE_NERD_A")
  LoadAnimationGroup("IDLE_NERD_B")
  LoadAnimationGroup("IDLE_NERD_C")
  LoadAnimationGroup("IDLE_NERD_D")
  LoadAnimationGroup("IDLE_NGIRL")
  LoadAnimationGroup("IDLE_PREP_A")
  LoadAnimationGroup("IDLE_PREP_B")
  LoadAnimationGroup("IDLE_PREP_C")
  LoadAnimationGroup("IDLE_PREP_D")
  LoadAnimationGroup("IDLE_SEXY_A")
  LoadAnimationGroup("IDLE_SEXY_B")
  LoadAnimationGroup("IDLE_SEXY_C")
  LoadAnimationGroup("INDgateC")
  LoadAnimationGroup("JPhoto")
  LoadAnimationGroup("JunkCarA")
  LoadAnimationGroup("JV_Asylum")
  LoadAnimationGroup("J_Damon")
  LoadAnimationGroup("J_Grappler")
  LoadAnimationGroup("J_Melee")
  LoadAnimationGroup("J_Ranged")
  LoadAnimationGroup("J_Striker")
  LoadAnimationGroup("KISS1")
  LoadAnimationGroup("KISS2")
  LoadAnimationGroup("KISS3")
  LoadAnimationGroup("KISS4")
  LoadAnimationGroup("KissAdult")
  LoadAnimationGroup("KISSB")
  LoadAnimationGroup("KISSF")
  LoadAnimationGroup("LckrGymA")
  LoadAnimationGroup("LE_Officer")
  LoadAnimationGroup("LE_Orderly")
  LoadAnimationGroup("Mermaid")
  LoadAnimationGroup("MG_Craps")
  LoadAnimationGroup("MINIBIKE")
  LoadAnimationGroup("MINICHEM")
  LoadAnimationGroup("MINIDARTS")
  LoadAnimationGroup("MINIDunk")
  LoadAnimationGroup("MINIGraf")
  LoadAnimationGroup("MINIHACKY")
  LoadAnimationGroup("MINI_Arm")
  LoadAnimationGroup("MINI_BallToss")
  LoadAnimationGroup("MINI_Lock")
  LoadAnimationGroup("MINI_React")
  LoadAnimationGroup("Miracle")
  LoadAnimationGroup("MOWER")
  LoadAnimationGroup("MPostA")
  LoadAnimationGroup("N2B Dishonerable")
  LoadAnimationGroup("Nemesis")
  LoadAnimationGroup("nerdBar1")
  LoadAnimationGroup("NIS_0_00A")
  LoadAnimationGroup("NIS_1_02")
  LoadAnimationGroup("NIS_1_02B")
  LoadAnimationGroup("NIS_1_03")
  LoadAnimationGroup("NIS_1_04")
  LoadAnimationGroup("NIS_1_05")
  LoadAnimationGroup("NIS_1_07")
  LoadAnimationGroup("NIS_1_08_1")
  LoadAnimationGroup("NIS_1_09")
  LoadAnimationGroup("NIS_1_11")
  LoadAnimationGroup("NIS_2_01")
  LoadAnimationGroup("NIS_2_03")
  LoadAnimationGroup("NIS_2_04")
  LoadAnimationGroup("NIS_2_06_1")
  LoadAnimationGroup("NIS_2_B")
  LoadAnimationGroup("NIS_2_S04")
  LoadAnimationGroup("NIS_3_01")
  LoadAnimationGroup("NIS_3_02")
  LoadAnimationGroup("NIS_3_04")
  LoadAnimationGroup("NIS_3_05")
  LoadAnimationGroup("NIS_3_06")
  LoadAnimationGroup("NIS_3_08")
  LoadAnimationGroup("NIS_3_11")
  LoadAnimationGroup("NIS_3_B")
  LoadAnimationGroup("NIS_3_G3")
  LoadAnimationGroup("NIS_3_R09_D")
  LoadAnimationGroup("NIS_3_R09_G")
  LoadAnimationGroup("NIS_3_R09_J")
  LoadAnimationGroup("NIS_3_R09_N")
  LoadAnimationGroup("NIS_3_R09_P")
  LoadAnimationGroup("NIS_3_S03")
  LoadAnimationGroup("NIS_3_S03_B")
  LoadAnimationGroup("NIS_3_S11")
  LoadAnimationGroup("NIS_4_01")
  LoadAnimationGroup("NIS_4_05")
  LoadAnimationGroup("NIS_4_06")
  LoadAnimationGroup("NIS_4_B2")
  LoadAnimationGroup("NIS_5_01")
  LoadAnimationGroup("NIS_5_02")
  LoadAnimationGroup("NIS_5_03")
  LoadAnimationGroup("NIS_5_04")
  LoadAnimationGroup("NIS_5_05")
  LoadAnimationGroup("NIS_5_07")
  LoadAnimationGroup("NIS_5_G5")
  LoadAnimationGroup("NIS_6_02")
  LoadAnimationGroup("NIS_6_03")
  LoadAnimationGroup("NLock01A")
  LoadAnimationGroup("NPC_Adult")
  LoadAnimationGroup("NPC_AggroTaunt")
  LoadAnimationGroup("NPC_Chat_1")
  LoadAnimationGroup("NPC_Chat_2")
  LoadAnimationGroup("NPC_Chat_F")
  LoadAnimationGroup("NPC_Cheering")
  LoadAnimationGroup("NPC_Love")
  LoadAnimationGroup("NPC_Mascot")
  LoadAnimationGroup("NPC_NeedsResolving")
  LoadAnimationGroup("NPC_Principal")
  LoadAnimationGroup("NPC_Shopping")
  LoadAnimationGroup("NPC_Spectator")
  LoadAnimationGroup("N_Ranged")
  LoadAnimationGroup("N_Striker")
  LoadAnimationGroup("N_Striker_A")
  LoadAnimationGroup("N_Striker_B")
  LoadAnimationGroup("ObsDoor")
  LoadAnimationGroup("OBSMotor")
  LoadAnimationGroup("ObsPtf_1")
  LoadAnimationGroup("ObsPtf_2")
  LoadAnimationGroup("Pageant")
  LoadAnimationGroup("PedCoaster")
  LoadAnimationGroup("Player_Tired")
  LoadAnimationGroup("Player_VTired")
  LoadAnimationGroup("POI_Booktease")
  LoadAnimationGroup("POI_Cafeteria")
  LoadAnimationGroup("POI_ChLead")
  LoadAnimationGroup("POI_Gen")
  LoadAnimationGroup("POI_Smoking")
  LoadAnimationGroup("POI_Telloff")
  LoadAnimationGroup("POI_WarmHands")
  LoadAnimationGroup("POI_Worker")
  LoadAnimationGroup("PortaPoo")
  LoadAnimationGroup("PrepDoor")
  LoadAnimationGroup("PunchBag")
  LoadAnimationGroup("pxHoop")
  LoadAnimationGroup("pxLad10M")
  LoadAnimationGroup("Px_Arcade")
  LoadAnimationGroup("Px_Bed")
  LoadAnimationGroup("Px_Fountain")
  LoadAnimationGroup("Px_Garb")
  LoadAnimationGroup("Px_Gen")
  LoadAnimationGroup("Px_Ladr")
  LoadAnimationGroup("Px_Rail")
  LoadAnimationGroup("Px_RedButton")
  LoadAnimationGroup("Px_Sink")
  LoadAnimationGroup("Px_Tlet")
  LoadAnimationGroup("Px_Tree")
  LoadAnimationGroup("P_Grappler")
  LoadAnimationGroup("P_Striker")
  LoadAnimationGroup("QPed")
  LoadAnimationGroup("RAT_PED")
  LoadAnimationGroup("Reeper")
  LoadAnimationGroup("RMailbox")
  LoadAnimationGroup("Russell")
  LoadAnimationGroup("Russell_PBomb")
  LoadAnimationGroup("Santa_Lap")
  LoadAnimationGroup("SAUTH_A")
  LoadAnimationGroup("SAUTH_F")
  LoadAnimationGroup("SAUTH_U")
  LoadAnimationGroup("SAUTH_X")
  LoadAnimationGroup("SBarels1")
  LoadAnimationGroup("SBULL_A")
  LoadAnimationGroup("SBULL_F")
  LoadAnimationGroup("SBULL_S")
  LoadAnimationGroup("SBULL_U")
  LoadAnimationGroup("SBULL_X")
  LoadAnimationGroup("Scaffold")
  LoadAnimationGroup("SCbanpil")
  LoadAnimationGroup("SCBell")
  LoadAnimationGroup("SCDoor")
  LoadAnimationGroup("ScGate")
  LoadAnimationGroup("SCgrdoor")
  LoadAnimationGroup("scObsDr")
  LoadAnimationGroup("ScoolBus")
  LoadAnimationGroup("SCOOTER")
  LoadAnimationGroup("SecDoorL")
  LoadAnimationGroup("SecDoorR")
  LoadAnimationGroup("Sedan")
  LoadAnimationGroup("SFAT_A")
  LoadAnimationGroup("SFAT_F")
  LoadAnimationGroup("SFAT_I")
  LoadAnimationGroup("SFAT_S")
  LoadAnimationGroup("SGEN_A")
  LoadAnimationGroup("SGEN_F")
  LoadAnimationGroup("SGEN_I")
  LoadAnimationGroup("SGEN_S")
  LoadAnimationGroup("SGIRLS")
  LoadAnimationGroup("SGIRL_A")
  LoadAnimationGroup("SGIRL_D")
  LoadAnimationGroup("SGIRL_F")
  LoadAnimationGroup("SGIRL_S")
  LoadAnimationGroup("SGTargB")
  LoadAnimationGroup("ShopBike")
  LoadAnimationGroup("SHUMIL_01")
  LoadAnimationGroup("SHWR")
  LoadAnimationGroup("SIAMESE")
  LoadAnimationGroup("Siamese2")
  LoadAnimationGroup("Sitting_Boys")
  LoadAnimationGroup("SK8Board")
  LoadAnimationGroup("Skateboard")
  LoadAnimationGroup("SkeltonMan")
  LoadAnimationGroup("Slingsh")
  LoadAnimationGroup("SNERD_A")
  LoadAnimationGroup("SNERD_F")
  LoadAnimationGroup("SNERD_I")
  LoadAnimationGroup("SNERD_S")
  LoadAnimationGroup("SNGIRLS")
  LoadAnimationGroup("SNGIRL_D")
  LoadAnimationGroup("SNGIRL_F")
  LoadAnimationGroup("SnowBlob")
  LoadAnimationGroup("SnowMND")
  LoadAnimationGroup("SnowWall")
  LoadAnimationGroup("SOLD_A")
  LoadAnimationGroup("SOLD_F")
  LoadAnimationGroup("SOLD_I")
  LoadAnimationGroup("SOLD_S")
  LoadAnimationGroup("SPLAY_A")
  LoadAnimationGroup("SPLAY_B")
  LoadAnimationGroup("SprayCan")
  LoadAnimationGroup("SpudG")
  LoadAnimationGroup("Squid")
  LoadAnimationGroup("StalDoor")
  LoadAnimationGroup("Straf_Dout")
  LoadAnimationGroup("Straf_Fat")
  LoadAnimationGroup("Straf_Female")
  LoadAnimationGroup("Straf_Male")
  LoadAnimationGroup("Straf_Nerd")
  LoadAnimationGroup("Straf_Prep")
  LoadAnimationGroup("Straf_Savage")
  LoadAnimationGroup("Straf_Wrest")
  LoadAnimationGroup("SUV")
  LoadAnimationGroup("TadGates")
  LoadAnimationGroup("TadShud")
  LoadAnimationGroup("TE_Female")
  LoadAnimationGroup("TGKFlag")
  LoadAnimationGroup("ToolBox")
  LoadAnimationGroup("TrackSW")
  LoadAnimationGroup("TreeFall")
  LoadAnimationGroup("Truck")
  LoadAnimationGroup("Try_Clothes")
  LoadAnimationGroup("TSGate")
  LoadAnimationGroup("UBO")
  LoadAnimationGroup("Umbrella")
  LoadAnimationGroup("VDMilo")
  LoadAnimationGroup("VFlytrap")
  LoadAnimationGroup("V_Bike")
  LoadAnimationGroup("V_Bike_Races")
  LoadAnimationGroup("V_COPBIKE")
  LoadAnimationGroup("V_SCOOTER")
  LoadAnimationGroup("WBalloon")
  LoadAnimationGroup("WeaponUnlock")
  LoadAnimationGroup("Ween_Fem")
  LoadAnimationGroup("WHCrane")
  LoadAnimationGroup("WheelBrl")
  LoadAnimationGroup("WPCannon")
  LoadAnimationGroup("WPSheldB")
  LoadAnimationGroup("WPShield")
  LoadAnimationGroup("WPTurret")
  LoadAnimationGroup("W_BBall")
  LoadAnimationGroup("W_BBallBat")
  LoadAnimationGroup("W_BRocket")
  LoadAnimationGroup("W_Camera")
  LoadAnimationGroup("W_CherryBomb")
  LoadAnimationGroup("W_CHShield")
  LoadAnimationGroup("W_FlashLight")
  LoadAnimationGroup("W_Fountain")
  LoadAnimationGroup("W_Itchpowder")
  LoadAnimationGroup("W_JBroom")
  LoadAnimationGroup("W_Lid")
  LoadAnimationGroup("W_PooBag")
  LoadAnimationGroup("W_PRANK")
  LoadAnimationGroup("W_Slingshot")
  LoadAnimationGroup("W_Snowball")
  LoadAnimationGroup("W_snowshwl")
  LoadAnimationGroup("W_SprayCan")
  LoadAnimationGroup("W_SpudGun")
  LoadAnimationGroup("W_Stick")
  LoadAnimationGroup("W_Thrown")
  LoadAnimationGroup("W_wtrpipe")
  LoadAnimationGroup("x_cas1")
  LoadAnimationGroup("x_cas2")
  LoadAnimationGroup("x_cas3")
  LoadAnimationGroup("x_ccane")
  LoadAnimationGroup("X_Chair")
  LoadAnimationGroup("x_cndl")
  LoadAnimationGroup("x_sleigh")
  LoadAnimationGroup("x_tedy")
  LoadActionTree("Act/Conv/3_05.act")
  LoadActionTree("Act/AI/AI_Norton.act")
  LoadActionTree("Act/Anim/3_05_Norton.act")
  LoadActionTree("Act/Conv/1_G1.act")
  LoadActionTree("Act/Anim/DO_Edgar.act")
  LoadActionTree("Act/AI/AI_EDGAR_5_B.act")
  LoadActionTree("Act/Conv/5_B.act")
end


function PedsPrepareConversation(ped1, ped2, distance, walkSpeed)
  PlayerSetPunishmentPoints(0)
  if PedGetWeapon(gPlayer) == 437 then
    PedSetWeapon(gPlayer, -1)
  end
  if PedIsInAnyVehicle(gPlayer) then
    PedWarpOutOfCar(gPlayer)
  end
  PedStop(ped2)
  local x, y, z = PedGetPosXYZ(ped2)
  PedMoveToXYZ(ped1, walkSpeed, x, y, z)
  local r1 = x + distance
  local r2 = y + distance
  local r3 = x - distance
  local r4 = y - distance
  x, y, z = PedGetPosXYZ(ped1)
  PedFaceXYZ(ped2, x, y, z)
  repeat
    Wait(0)
  until PedInRectangle(ped1, r1, r2, r3, r4)
  PedStop(ped1)
  x, y, z = PedGetPosXYZ(ped2)
  PedFaceXYZ(ped1, x, y, z)
  x, y, z = PedGetPosXYZ(ped1)
  PedFaceXYZ(ped2, x, y, z)
end





function main()
  ClockSet(9, 30)
  TextPrintString("Meet With Saleh Outside!", 4, 1)
  PedClearAllWeapons(gPlayer)
  Saleh = PedCreateXYZ(32, 270, -101, 6)
  PedClearAllWeapons(Saleh)
  BlipS = AddBlipForChar(Saleh, 0, 0, 4)
  repeat
    if PedIsDead(Saleh) then
      MissionFail()
    end
    Wait(0)
  until PedIsInAreaXYZ(gPlayer, 270, -101, 6, 2)
  BlipRemove(BlipS)
  PlayerSetControl(0)
  CameraSetFOV(65)
  Wait(2000)
  CameraSetFOV(40)
  CameraSetWidescreen(true)
  PedsPrepareConversation(gPlayer, Saleh, 1, 0)
  SoundRemoveAllQueuedSpeech(Saleh, true)
  Wait(2000)
  PedSetActionNode(Saleh, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Saleh: Something terrible has happened.", 2, 2)
  SoundRemoveAllQueuedSpeech(Saleh, true)
  Wait(2000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: What is it Saleh what happened?", 2, 2)
  SoundRemoveAllQueuedSpeech(Saleh, true)
  Wait(2000)
  PedSetActionNode(Saleh, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Saleh: The biggest bitch ABO-J3FR Is going to kick my ass of the school!", 4, 2)
  SoundRemoveAllQueuedSpeech(Saleh, true)
  Wait(4000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: Oh ABO-J3FR hah ?, I will fuck him hard cuz...", 3, 2)
  SoundRemoveAllQueuedSpeech(Saleh, true)
  Wait(3000)
  PedSetActionNode(Saleh, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Saleh: cuz What ?? tell me Jimmy!", 3, 2)
  SoundRemoveAllQueuedSpeech(Saleh, true)
  Wait(3000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: That bitch he ruind my Life... a lot of things.. forget it Saleh!", 3, 2)
  SoundRemoveAllQueuedSpeech(Saleh, true)
  Wait(3000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: I will revenge to Our Case BRO!", 2, 2)
  SoundRemoveAllQueuedSpeech(Saleh, true)
  Wait(2000)
  PedSetActionNode(Saleh, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Saleh: Nice Jimmy, I'm waiting! now listen I will go to drink 'Black'.. See You Later", 4, 2)
  SoundRemoveAllQueuedSpeech(Saleh, true)
  Wait(4000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: See You Later", 2, 2)
  SoundRemoveAllQueuedSpeech(Saleh, true)
  Wait(3000)
  PedSetInfiniteSprint(Saleh, true)
  Wait(500)
  CameraReset()
  CameraReturnToPlayer()
  CameraSetWidescreen(false)
  SoundSetAudioFocusPlayer()
  PlayerSetControl(1)
  PedMoveToXYZ(Saleh, 2, 210, -80, 8)
  TextPrintString("Go to ALI-ALJBAR Under The School!", 5, 1)
  AliALJBAR = PedCreateXYZ(8, -738, -50, 9)
  BlipAli = AddBlipForChar(AliALJBAR, 0, 0, 4)
  repeat
    if PedIsInAreaXYZ(gPlayer, 271, -122, 6, 2) then
      MissionFail()
    end
    Wait(0)
  until PedIsInAreaXYZ(gPlayer, -738, -50, 9, 2)
  SoundPlayStream("MS_StealthLow.rsm", 0.6)
  BlipRemove(BlipAli)
  PlayerSetControl(0)
  CameraSetFOV(65)
  Wait(2000)
  CameraSetFOV(40)
  CameraSetWidescreen(true)
  PedsPrepareConversation(gPlayer, AliALJBAR, 1, 0)
  SoundRemoveAllQueuedSpeech(AliALJBAR, true)
  Wait(2000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: Hey Ya 7mar! Where ABO-J3FR? Snitch", 5, 2)
  SoundRemoveAllQueuedSpeech(AliALJBAR, true)
  Wait(5000)
  PedSetActionNode(AliALJBAR, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Ali-ALJBAR: i won't tell you Jimmy.... I will make your life Ruind Than you Think!", 5, 2)
  SoundRemoveAllQueuedSpeech(AliALJBAR, true)
  Wait(5000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: Okay i will teach you a lesson!", 3, 2)
  SoundRemoveAllQueuedSpeech(AliALJBAR, true)
  Wait(3000)
  SoundPlayInteractiveStream("MS_BikeFunLow.rsm", 0.5)
  SoundSetMidIntensityStream("MS_BikeFunMid.rsm", 0.6)
  SoundSetHighIntensityStream("MS_BikeFunHigh.rsm", 0.6)
  PedDelete(Saleh)
  CameraReset()
  CameraReturnToPlayer()
  CameraSetWidescreen(false)
  SoundSetAudioFocusPlayer()
  PlayerSetControl(1)
  PedSetPedToTypeAttitude(AliALJBAR, 13, 0)
  PedAttackPlayer(AliALJBAR, 3)
  AddBlipForChar(AliALJBAR, 0, 26, 4)
  repeat
    if PedIsInAreaXYZ(gPlayer, 271, -122, 6, 2) then
      MissionFail()
    end
    Wait(0)
  until PedIsDead(AliALJBAR)
  TextPrintString("Keep Going and Beat Abo-ALmsag And AliNaeem!", 4, 1)
  AfterPedIsDead()
end





function AfterPedIsDead()
  enemy1 = PedCreateXYZ(139, -748, -71, 8)
  enemy2 = PedCreateXYZ(71, -735, -62, 8)
  repeat
    Wait(0)
  until PedIsInAreaXYZ(gPlayer, -747, -57, 9, 3)
  PedSetPedToTypeAttitude(enemy1, 13, 0)
  PedAttackPlayer(enemy1, 3)
  PedSetPedToTypeAttitude(enemy2, 13, 0)
  PedAttackPlayer(enemy2, 3)
  AddBlipForChar(enemy1, 0, 26, 4)
  AddBlipForChar(enemy2, 0, 26, 4)
  repeat
    if PedIsInAreaXYZ(gPlayer, 271, -122, 6, 2) then
      MissionFail()
    end
    Wait(0)
  until PedAreDead()
  TextPrintString("Keep Going", 2, 1)
  Runner1 = PedCreateXYZ(102, -745, -85, 8)
  Runner2 = PedCreateXYZ(146, -746, -84, 8)
  repeat
    if PedIsInAreaXYZ(gPlayer, 271, -122, 6, 2) then
      MissionFail()
    end
    Wait(0)
  until PedIsInAreaXYZ(gPlayer, -736, -74, 8, 4)
  GameSetPedStat(Runner1, 20, 150)
  GameSetPedStat(Runner2, 20, 150)
  PedMoveToXYZ(Runner1, 2, -771, -125, 7)
  PedMoveToXYZ(Runner2, 2, -771, -125, 7)
  blipRunner1 = AddBlipForChar(Runner1, 0, 26, 4)
  blipRunner2 = AddBlipForChar(Runner2, 0, 26, 4)
  Astad1 = PedCreateXYZ(49, -757, -51, 9)
  Astad2 = PedCreateXYZ(51, -755, -51, 9)
  PedSetInfiniteSprint(Runner1, true)
  PedSetInfiniteSprint(Runner2, true)
  BLastMission()
end
function PedAreDead()
  if PedIsDead(enemy1) and PedIsDead(enemy2) then
    return true
  end
  return false
end







function BLastMission()
  TextPrintString("They are running! Go after them and beat them!", 4, 2)
  repeat
    if PedIsInAreaXYZ(gPlayer, 271, -122, 6, 2) then
      MissionFail()
    end
    if PedIsDeadRunners() then
      TextPrintString("Now go to Prefects", 3, 1)
    end
    Wait(0)
  until PedIsInAreaXYZ(Runner1, -757, -69, 8, 3) or PedIsInAreaXYZ(Runner2, -757, -69, 8, 3) or PedIsDeadRunners()
  BlipRemove(blipRunner1)
  BlipRemove(blipRunner2)
  PedMoveToXYZ(Astad1, 2, -758, -63, 9)
  PedMoveToXYZ(Astad2, 2, -756, -63, 9)
  PedSetInvulnerable(Astad1, true)
  PedSetInvulnerable(Astad2, true)
  repeat
    if PedIsInAreaXYZ(gPlayer, 271, -122, 6, 2) then
      MissionFail()
    end
    Wait(0)
  until PedIsInAreaXYZ(gPlayer, -757, -69, 8, 3)
  PlayerSetControl(0)
  CameraSetFOV(65)
  Wait(2000)
  CameraSetFOV(40)
  CameraSetWidescreen(true)
  PedsPrepareConversation(gPlayer, Astad1, 2, 0)
  SoundRemoveAllQueuedSpeech(Astad1, true)
  Wait(2000)
  PedSetActionNode(Astad1, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Abo-Hayder: What are you doing here ?", 5, 2)
  SoundRemoveAllQueuedSpeech(Astad1, true)
  Wait(5000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: I want to Get out of here and see ABO-J3FR!", 5, 2)
  SoundRemoveAllQueuedSpeech(Astad1, true)
  Wait(5000)
  PedSetActionNode(Astad1, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Abo-Hayder: Ohh... But Before you go... you have to face the consequences!", 5, 2)
  SoundRemoveAllQueuedSpeech(Astad1, true)
  Wait(5000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: Suck My DICK!", 4, 2)
  SoundRemoveAllQueuedSpeech(Astad1, true)
  Wait(5000)
  PedDelete(Runner1)
  PedDelete(Runner2)
  SoundPlayStream("MS_BikeFunHigh.rsm", 0.6)
  PedSetInvulnerable(Astad1, false)
  PedSetInvulnerable(Astad2, false)
  CameraReset()
  CameraReturnToPlayer()
  CameraSetWidescreen(false)
  SoundSetAudioFocusPlayer()
  PlayerSetControl(1)
  PedSetActionTree(Astad2, "/Global/G_Striker_A", "Act/Anim/G_Striker_A.act")
  PedSetActionTree(Astad1, "/Global/G_Striker_A", "Act/Anim/G_Striker_A.act")
  PlayerSetPunishmentPoints(50)
  PedSetPedToTypeAttitude(Astad1, 13, 0)
  PedAttackPlayer(Astad1, 3)
  PedSetPedToTypeAttitude(Astad2, 13, 0)
  PedAttackPlayer(Astad2, 3)
  repeat
    if PedIsInAreaXYZ(gPlayer, 271, -122, 6, 2) then
      MissionFail()
    end
    Wait(0)
  until PedIsDeadAstad()
  LastMission()
end





function PedIsDeadRunners()
  if PedIsDead(Runner1) and PedIsDead(Runner2) then
    return true
  end
  return false
end





function PedIsDeadAstad()
  if PedIsDead(Astad1) and PedIsDead(Astad2) then
    return true
  end
  return false
end






function LastMission()
  SoundPlayInteractiveStream("MS_BikeFunLow.rsm", 0.5)
  SoundSetMidIntensityStream("MS_BikeFunMid.rsm", 0.6)
  SoundSetHighIntensityStream("MS_BikeFunHigh.rsm", 0.6)
  TextPrintString("Go to See 3wa!", 5, 1)
  Awa = PedCreateXYZ(61, -634, -286, 5)
  PedFaceXYZ(Awa, -633, -292, 5)
  BlipAwa = AddBlipForChar(Awa, 0, 0, 4)
  PedSetInvulnerable(Awa, true)
  repeat
    Wait(0)
  until PedIsInAreaXYZ(gPlayer, -633, -292, 5, 3)
  PlayerSetControl(0)
  Wait(2000)
  CameraSetWidescreen(true)
  PedsPrepareConversation(gPlayer, Awa, 4, 0)
  x, y, z = PedGetPosXYZ(gPlayer)
  CameraSetXYZ(-636, -292, 10, x, y, z)
  SoundRemoveAllQueuedSpeech(Awa, true)
  Wait(2000)
  PedSetActionNode(Awa, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("3wa: What do you want jimmy ?", 3, 2)
  SoundRemoveAllQueuedSpeech(Awa, true)
  Wait(3000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: I wanna see your boss... ABO-J3FR!", 3, 2)
  SoundRemoveAllQueuedSpeech(Awa, true)
  Wait(3000)
  PedSetActionNode(Awa, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("3wa: he is busy.. now go to your class!", 3, 2)
  SoundRemoveAllQueuedSpeech(Awa, true)
  Wait(3000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: alright.. cool", 2, 2)
  SoundRemoveAllQueuedSpeech(Awa, true)
  Wait(3000)
  BlipRemove(BlipAwa)
  PedStop(Awa)
  CameraReset()
  CameraReturnToPlayer()
  CameraSetWidescreen(false)
  SoundSetAudioFocusPlayer()
  PlayerSetControl(1)
  TextPrintString("Go to get help from Saleh", 4, 1)
  Saleh1 = PedCreateXYZ(32, -535, 133, 46)
  Actor1 = PedCreateXYZ(30, -534, 133, 46)
  Actor2 = PedCreateXYZ(31, -535, 132, 46)
  PedsPrepareConversation(Saleh1, Actor1, 2, 0)
  PedsPrepareConversation(Actor2, Actor1, 2, 0)
  BlipS1 = AddBlipForChar(Saleh1, 0, 0, 4)
  repeat
    if PedIsDead(Saleh1) then
      MissionFail()
    end
    Wait(0)
  until PedIsInAreaXYZ(gPlayer, -535, 133, 46, 4)
  BlipRemove(BlipS1)
  PlayerSetControl(0)
  CameraSetFOV(65)
  Wait(2000)
  CameraSetFOV(40)
  CameraSetWidescreen(true)
  PedsPrepareConversation(gPlayer, Saleh1, 1, 0)
  SoundRemoveAllQueuedSpeech(Saleh1, true)
  Wait(2000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: i need help Saleh!.. come with me!", 3, 2)
  SoundRemoveAllQueuedSpeech(Saleh1, true)
  Wait(3000)
  PedSetActionNode(Saleh1, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Saleh: No Problem BRO!", 2, 2)
  SoundRemoveAllQueuedSpeech(Saleh1, true)
  Wait(2000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: Okay, the plan is to make chaos inside of the school!", 3, 2)
  SoundRemoveAllQueuedSpeech(Saleh1, true)
  Wait(3000)
  PedSetActionNode(Saleh1, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Saleh: For What ?", 2, 2)
  SoundRemoveAllQueuedSpeech(Saleh1, true)
  Wait(2000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: To make 3wa get out of his office! Then We go see ABO-J3FR... now follow me!", 4, 2)
  SoundRemoveAllQueuedSpeech(Saleh1, true)
  Wait(5000)
  CameraReset()
  CameraReturnToPlayer()
  CameraSetWidescreen(false)
  SoundSetAudioFocusPlayer()
  PlayerSetControl(1)
  PedRecruitAlly(gPlayer, Saleh1)
  PedSetAllyAutoEngage(Saleh1, true)
  Lead1 = PedCreateXYZ(99, -620, -304, 0)
  PedMoveToXYZ(Lead1, 0, -621, -308, 0)
  BlipLead1 = AddBlipForChar(Lead1, 0, 26, 4)
  PedSetHealth(Lead1, 1000)
  repeat
    Wait(0)
  until PedIsHit(Lead1, 2, 500)
  PedSetPedToTypeAttitude(Lead1, 13, 0)
  PedAttackPlayer(Lead1, 1)
  L1ActorCh1 = PedCreateXYZ(102, -605, -305, 0)
  PedRecruitAlly(Lead1, L1ActorCh1)
  PedSetAllyAutoEngage(L1ActorCh1, true)
  BlipActorCh1 = AddBlipForChar(L1ActorCh1, 0, 26, 4)
  Wait(250)
  L1ActorCh2 = PedCreateXYZ(85, -608, -303, 0)
  PedRecruitAlly(L1ActorCh1, L1ActorCh2)
  PedSetAllyAutoEngage(L1ActorCh2, true)
  BlipActorCh2 = AddBlipForChar(L1ActorCh2, 0, 26, 4)
  Wait(250)
  L1ActorCh3 = PedCreateXYZ(147, -606, -302, 0)
  PedRecruitAlly(L1ActorCh2, L1ActorCh3)
  PedSetAllyAutoEngage(L1ActorCh3, true)
  BlipActorCh3 = AddBlipForChar(L1ActorCh3, 0, 26, 4)
  Wait(250)
  L1ActorCh4 = PedCreateXYZ(145, -605, -302, 0)
  PedRecruitAlly(L1ActorCh3, L1ActorCh4)
  PedSetAllyAutoEngage(L1ActorCh4, true)
  BlipActorCh4 = AddBlipForChar(L1ActorCh4, 0, 26, 4)
  Wait(250)
  Wait(6000)
  Lead2 = PedCreateXYZ(37, -652, -309, 0)
  PedSetPedToTypeAttitude(Lead2, 11, 0)
  PedAttack(Lead2, Lead1, 3)
  Wait(2000)
  L2ActorCh1 = PedCreateXYZ(31, -648, -313, 0)
  PedSetAllyAutoEngage(L1ActorCh1, false)
  PedSetPedToTypeAttitude(L2ActorCh1, 11, 0)
  PedAttack(L2ActorCh1, L1ActorCh1, 3)
  PedSetPedToTypeAttitude(L1ActorCh1, 5, 0)
  PedAttack(L1ActorCh1, L2ActorCh1, 3)
  PedSetPedToTypeAttitude(Lead1, 5, 0)
  PedAttack(Lead1, Lead2, 3)
  Wait(2000)
  L2ActorCh2 = PedCreateXYZ(33, -651, -315, 0)
  PedSetPedToTypeAttitude(L2ActorCh2, 11, 0)
  PedAttack(L2ActorCh2, L1ActorCh2, 3)
  PedSetPedToTypeAttitude(L1ActorCh2, 5, 0)
  PedAttack(L1ActorCh2, L2ActorCh2, 3)
  Wait(2000)
  L2ActorCh3 = PedCreateXYZ(34, -652, -315, 0)
  PedSetPedToTypeAttitude(L2ActorCh3, 11, 0)
  PedAttack(L2ActorCh3, L1ActorCh3, 3)
  PedSetPedToTypeAttitude(L1ActorCh3, 5, 0)
  PedAttack(L1ActorCh3, L2ActorCh3, 3)
  Wait(2000)
  L2ActorCh4 = PedCreateXYZ(35, -648, -309, 0)
  PedSetPedToTypeAttitude(L2ActorCh4, 11, 0)
  PedAttack(L2ActorCh4, L1ActorCh4, 3)
  PedSetPedToTypeAttitude(L1ActorCh4, 5, 0)
  PedAttack(L1ActorCh4, L2ActorCh4, 3)
  Wait(10000)
  TextPrintString("Now go to hide from 3wa!", 4, 1)
  MakePedsIgnore()
  local x1, y1, z1 = PedGetPosXYZ(Lead2)
  PedMoveToXYZ(Awa, 2, x1, y1, z1)
  repeat
    Wait(0)
  until PedIsInAreaXYZ(Awa, -628, -307, 0, 5)
  PedSetPunishmentPoints(Lead1, 200)
  PedSetPunishmentPoints(Lead2, 200)
  TextPrintString("Now go to Upstairs with out get busted from 3wa!", 4, 1)
  BlipOffice = BlipAddXYZ(-629.51715, -280.86487, 5, 7, 2, 12)
  local nine, ten = -629.51715, -280.86487
  local r21 = nine + 1
  local r22 = ten + 1
  local r23 = nine - 1
  local r24 = ten - 1
  repeat
    Wait(0)
  until PedInRectangle(gPlayer, r21, r22, r23, r24)
  AreaTransitionXYZ(5, -701.2, 216.7, 31)
  PedDelete(Saleh1)
  BlipRemove(BlipOffice)
  AfterInOffice()
end



function MakePedsIgnore()
  PedSetPedToTypeAttitude(L2ActorCh1, 11, 3)
  PedAttack(L2ActorCh1, L1ActorCh1, 1)
  PedSetPedToTypeAttitude(L1ActorCh1, 5, 3)
  PedAttack(L1ActorCh1, L2ActorCh1, 1)
  PedSetPedToTypeAttitude(Lead1, 5, 3)
  PedAttack(Lead1, Lead2, 1)
  PedSetPedToTypeAttitude(Lead2, 11, 3)
  PedAttack(Lead2, Lead1, 1)
  PedSetPedToTypeAttitude(L2ActorCh2, 11, 3)
  PedAttack(L2ActorCh2, L1ActorCh2, 1)
  PedSetPedToTypeAttitude(L1ActorCh2, 5, 3)
  PedAttack(L1ActorCh2, L2ActorCh2, 1)
  PedSetPedToTypeAttitude(L2ActorCh3, 11, 3)
  PedAttack(L2ActorCh3, L1ActorCh3, 1)
  PedSetPedToTypeAttitude(L1ActorCh3, 5, 3)
  PedAttack(L1ActorCh3, L2ActorCh3, 1)
  PedSetPedToTypeAttitude(L2ActorCh4, 11, 3)
  PedAttack(L2ActorCh4, L1ActorCh4, 1)
  PedSetPedToTypeAttitude(L1ActorCh4, 5, 3)
  PedAttack(L1ActorCh4, L2ActorCh4, 1)
end



function AfterInOffice()
  AboJ3fr = PedCreateXYZ(65, -704, 205, 31)
  Zahr = PedCreateXYZ(8, -701, 206, 31)
  ActorOffice1 = PedCreateXYZ(4, -700, 204, 31)
  ActorOffice2 = PedCreateXYZ(7, -701, 203, 31)
  ActorOffice3 = PedCreateXYZ(6, -702, 203, 31)
  AminOffice = PedCreateXYZ(28, -700, 202, 31)
  PedClearAllWeapons(AboJ3fr)
  PedClearAllWeapons(Zahr)
  PedClearAllWeapons(ActorOffice1)
  PedClearAllWeapons(ActorOffice2)
  PedClearAllWeapons(ActorOffice3)
  PedClearAllWeapons(AminOffice)
  PedsPrepareConversation(AboJ3fr, Zahr, 10, 0)
  PedsPrepareConversation(Zahr, AboJ3fr, 10, 0)
  PedsPrepareConversation(ActorOffice1, AboJ3fr, 10, 0)
  PedsPrepareConversation(ActorOffice2, AboJ3fr, 10, 0)
  PedsPrepareConversation(ActorOffice3, AboJ3fr, 10, 0)
  PedsPrepareConversation(AminOffice, AboJ3fr, 10, 0)
  repeat
    Wait(0)
  until PedIsInAreaXYZ(gPlayer, -699, 216, 31, 4)
  PedDelete(Lead1)
  PedDelete(Lead2)
  PedDelete(L1ActorCh1)
  PedDelete(L1ActorCh2)
  PedDelete(L1ActorCh3)
  PedDelete(L1ActorCh4)
  PedDelete(L2ActorCh1)
  PedDelete(L2ActorCh2)
  PedDelete(L2ActorCh3)
  PedDelete(L2ActorCh4)
  PedDelete(Awa)
  PlayerSetControl(0)
  Wait(500)
  PedsPrepareConversation(gPlayer, AboJ3fr, 5, 0)
  CameraSetWidescreen(true)
  Wait(4000)
  PedsPrepareConversation(Zahr, AboJ3fr, 10, 0)
  PedsPrepareConversation(AboJ3fr, Zahr, 11, 0)
  SoundRemoveAllQueuedSpeech(AboJ3fr, true)
  SoundRemoveAllQueuedSpeech(Zahr, true)
  SoundRemoveAllQueuedSpeech(ActorOffice1, true)
  SoundRemoveAllQueuedSpeech(ActorOffice2, true)
  SoundRemoveAllQueuedSpeech(ActorOffice3, true)
  SoundRemoveAllQueuedSpeech(AminOffice, true)
  Wait(5000)
  CameraSetXYZ(-696, 200, 34, -701, 204, 31)
  Wait(500)
  PedSetActionNode(AboJ3fr, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("ABO-J3FR: **********************************************************************", 7, 2)
  SoundRemoveAllQueuedSpeech(AboJ3fr, true)
  SoundRemoveAllQueuedSpeech(Zahr, true)
  Wait(7000)
  PedSetActionNode(Zahr, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Zahr: **********************************************************************", 7, 2)
  SoundRemoveAllQueuedSpeech(AboJ3fr, true)
  SoundRemoveAllQueuedSpeech(Zahr, true)
  Wait(7000)
  PedSetActionNode(Zahr, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Zahr: **********************************************************************", 7, 2)
  SoundRemoveAllQueuedSpeech(AboJ3fr, true)
  SoundRemoveAllQueuedSpeech(Zahr, true)
  Wait(7000)
  PedSetActionNode(AboJ3fr, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("ABO-J3FR: **********************************************************************", 4, 2)
  SoundRemoveAllQueuedSpeech(AboJ3fr, true)
  SoundRemoveAllQueuedSpeech(Zahr, true)
  Wait(4000)
  PedSetActionNode(AboJ3fr, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("ABO-J3FR: **********************************************************************", 4, 2)
  SoundRemoveAllQueuedSpeech(AboJ3fr, true)
  SoundRemoveAllQueuedSpeech(Zahr, true)
  Wait(4000)
  PedSetActionNode(AminOffice, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Amin-ALmbeog: **********************************************************************", 3, 2)
  SoundRemoveAllQueuedSpeech(AboJ3fr, true)
  SoundRemoveAllQueuedSpeech(AminOffice, true)
  Wait(3000)
  PedSetActionNode(AboJ3fr, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("ABO-J3FR: **********************************************************************", 2.5, 2)
  SoundRemoveAllQueuedSpeech(AboJ3fr, true)
  SoundRemoveAllQueuedSpeech(AminOffice, true)
  Wait(2500)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: **********************************************************************", 4, 2)
  SoundRemoveAllQueuedSpeech(AboJ3fr, true)
  Wait(4000)
  PedSetActionNode(AboJ3fr, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("ABO-J3FR: **********************************************************************", 4, 2)
  SoundRemoveAllQueuedSpeech(AboJ3fr, true)
  Wait(4000)
  CameraReset()
  CameraReturnToPlayer()
  CameraSetWidescreen(false)
  CameraFade(2000, 0)
  Wait(1000)
  CameraFade(1000, 1)
  PedDelete(AboJ3fr)
  PedDelete(Zahr)
  PedDelete(ActorOffice1)
  PedDelete(ActorOffice2)
  PedDelete(ActorOffice3)
  PedDelete(AminOffice)
  PedDelete(Actor1)
  PedDelete(Actor2)
  PlayerSetControl(1)
  AboJ3frFOffice = PedCreateXYZ(65, -700, 204, 31)
  PedSetPedToTypeAttitude(AboJ3frFOffice, 13, 0)
  PedAttackPlayer(AboJ3frFOffice, 3)
  SoundPlayStream("MS_BikeFunHigh.rsm", 0.6)
  PedShowHealthBar(AboJ3frFOffice, true, "N_DrCrabblesnitch", true)
  PedSetActionTree(AboJ3frFOffice, "/Global/G_Striker_A", "Act/Anim/G_Striker_A.act")
  PlayerSetPunishmentPoints(50)
  PedSetDamageGivenMultiplier(AboJ3frFOffice, 2, 200)
  PlayerHP = PedGetHealth(gPlayer)
  PlayerMaxHP = PedGetMaxHealth(gPlayer)
  PlayerSocialDisableActionAgainstPed(AboJ3frFOffice, 35, true)
  repeat
    if PedGetHealth(gPlayer) <= 20 then
      PedSetHealth(gPlayer, PlayerMaxHP)
    end
    if PedGetHealth(AboJ3frFOffice) <= 100 then
      PedSetHealth(AboJ3frFOffice, PlayerMaxHP)
    end
    Wait(0)
  until PedGetHealth(gPlayer) <= 30
  SoundPlayInteractiveStream("MS_BikeFunLow.rsm", 0.5)
  SoundSetMidIntensityStream("MS_BikeFunMid.rsm", 0.6)
  SoundSetHighIntensityStream("MS_BikeFunHigh.rsm", 0.6)
  PlayerSetPunishmentPoints(0)
  PedSetStationary(AboJ3frFOffice, true)
  PedSetPedToTypeAttitude(AboJ3frFOffice, 13, 3)
  PedAttackPlayer(AboJ3frFOffice, -1)
  PedSetHealth(gPlayer, 1)
  PedShowHealthBar(AboJ3frFOffice, false, "N_DrCrabblesnitch", false)
  PedSetActionNode(gPlayer, "/Global/1_07/KO_COLLAPSE", "Act/Conv/1_07.act")
  Wait(1500)
  PedSetActionNode(gPlayer, "/Global/HitTree/KnockOuts/BoxingSpecialKO/BoxingSpeicalKO/Knockout/KnockoutDead", "Act/HitTree.act")
  Wait(3000)
  PedSetActionNode(AboJ3frFOffice, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("ABO-J3FR: Next time think before you face me", 4, 2)
  SoundRemoveAllQueuedSpeech(AboJ3frFOffice, true)
  Wait(4000)
  PedSetActionNode(AboJ3frFOffice, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("ABO-J3FR: 3WWWWWAAAAAAA!!!! Come to take the trash out!!", 4, 2)
  SoundRemoveAllQueuedSpeech(AboJ3frFOffice, true)
  Wait(4000)
  CameraFade(2000, 0)
  PlayerSetPunishmentPoints(0)
  AreaTransitionXYZ(2, -633, -291, 5)
  PedSetHealth(gPlayer, PlayerMaxHP)
  PedDelete(AboJ3frFOffice)
  PedFaceXYZ(gPlayer, -633, -292, 5)
  TextPrintString("Now Go Find Khader inside the school", 5, 1)
  Khader = PedCreateXYZ(151, -583, -333, 5)
  PedSetStationary(Khader, true)
  PedSetInvulnerable(Khader, true)
  PedFaceXYZ(Khader, -584, -323, 5)
  Wait(5000)
  BlipKhader = AddBlipForChar(Khader, 0, 0, 4)
  local x, y = -584, -323
  local r1 = x + 3
  local r2 = y + 3
  local r3 = x - 3
  local r4 = y - 3
  repeat
    PedSetPunishmentPoints(Khader, 0)
    Wait(0)
  until PedInRectangle(gPlayer, r1, r2, r3, r4)
  BlipRemove(BlipKhader)
  PedsPrepareConversation(gPlayer, Khader, 2, 0)
  PlayerSetControl(0)
  Wait(500)
  CameraSetWidescreen(true)
  CameraSetXYZ(-585, -324, 7)
  local x, y, z = PedGetPosXYZ(Khader)
  CameraLookAtXYZ(x, y, z)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: Khader... why are you in Ladies bathr..... forget it", 4, 2)
  SoundRemoveAllQueuedSpeech(Khader, true)
  Wait(4000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: I want your wise Teacher.. i have to kill ABO-J3FR!!", 4, 2)
  SoundRemoveAllQueuedSpeech(Khader, true)
  Wait(4000)
  PedSetActionNode(Khader, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Khader: Look.. My steps walking to you..... And my wise walking to you.", 5, 2)
  SoundRemoveAllQueuedSpeech(Khader, true)
  Wait(5000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: OMG.. now i feel can beat ABO-J3FR...", 3, 2)
  SoundRemoveAllQueuedSpeech(Khader, true)
  Wait(3000)
  PedSetActionNode(Khader, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Khader: Okay now get out of here... i have Business to do here!", 4, 2)
  SoundRemoveAllQueuedSpeech(Khader, true)
  Wait(5000)
  PlayerSetControl(1)
  PedSetInvulnerable(Khader, false)
  CameraReset()
  CameraReturnToPlayer()
  CameraSetWidescreen(false)
  repeat
    if PedIsDead(Khader) then
      MissionFail()
    end
    Wait(0)
  until PedIsInAreaXYZ(gPlayer, -584, -323, 5, 2)
  Saleh2 = PedCreateXYZ(32, -535, 133, 46)
  ActorForS1 = PedCreateXYZ(30, -534, 133, 46)
  ActorForS2 = PedCreateXYZ(31, -535, 132, 46)
  PedsPrepareConversation(Saleh2, ActorForS1, 2, 0)
  PedsPrepareConversation(ActorForS2, ActorForS1, 2, 0)
  Wait(500)
  BlipS2 = AddBlipForChar(Saleh2, 0, 0, 4)
  repeat
    Wait(0)
  until PedIsInAreaXYZ(gPlayer, -535, 133, 46, 4)
  BlipRemove(BlipS2)
  PlayerSetControl(0)
  CameraSetFOV(65)
  Wait(2000)
  CameraSetFOV(40)
  CameraSetWidescreen(true)
  PedsPrepareConversation(gPlayer, Saleh2, 1, 0)
  SoundRemoveAllQueuedSpeech(Saleh2, true)
  Wait(2000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: Saleh... Now i can Beat ABO-J3FR.. we can", 3, 2)
  SoundRemoveAllQueuedSpeech(Saleh2, true)
  Wait(3000)
  PedSetActionNode(Saleh2, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Saleh: Really ?...", 2, 2)
  SoundRemoveAllQueuedSpeech(Saleh2, true)
  Wait(2000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: talk to your friends... we need them..", 3, 2)
  SoundRemoveAllQueuedSpeech(Saleh2, true)
  Wait(3000)
  PedSetActionNode(Saleh2, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Saleh: No Problem... So be it!", 2, 2)
  SoundRemoveAllQueuedSpeech(Saleh2, true)
  Wait(3000)
  TextPrintString("Go to and take ABO-J3FR to the HOLE!", 7, 1)
  CameraReset()
  CameraReturnToPlayer()
  CameraSetWidescreen(false)
  SoundSetAudioFocusPlayer()
  PlayerSetControl(1)
  Fz3a1 = PedCreateXYZ(31, -538, 144, 50)
  Fz3a2 = PedCreateXYZ(33, -532, 142, 50)
  Fz3a3 = PedCreateXYZ(34, -532, 144, 50)
  Fz3a4 = PedCreateXYZ(35, -538, 142, 50)
  PedRecruitAlly(gplayer, Saleh2)
  PedRecruitAlly(Saleh2, ActorForS1)
  PedRecruitAlly(ActorForS1, ActorForS2)
  PedRecruitAlly(ActorForS2, Fz3a1)
  PedRecruitAlly(Fz3a1, Fz3a2)
  PedRecruitAlly(Fz3a2, Fz3a3)
  PedRecruitAlly(Fz3a3, Fz3a4)
  Az3l = PedCreateXYZ(57, -630, -306, 0)
  PedMoveToXYZ(Az3l, 0, -627.3, -306, 0)
  JuseForBlip = PedCreateXYZ(65, -629, -280, 5)
  JustBlip = AddBlipForChar(JuseForBlip, 0, 0, 4)
  repeat
    Wait(0)
  until PedIsInAreaXYZ(gPlayer, -627.3, -306, 0, 4)
  BlipRemove(JustBlip)
  PedDelete(JuseForBlip)
  PlayerSetControl(0)
  PedsPrepareConversation(Az3l, gPlayer, 2, 0)
  Wait(1500)
  CameraSetWidescreen(true)
  CameraSetXYZ(-628, -307, 5)
  local x, y, z = PedGetPosXYZ(gPlayer)
  CameraLookAtXYZ(x, y, z)
  SoundRemoveAllQueuedSpeech(Az3l, true)
  Wait(2000)
  PedSetActionNode(Az3l, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("5z3l: Antm yly b8to al may ?", 4, 2)
  SoundRemoveAllQueuedSpeech(Az3l, true)
  Wait(4000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: La ya 5z3l...", 2, 2)
  SoundRemoveAllQueuedSpeech(Az3l, true)
  Wait(2000)
  PedSetActionNode(Az3l, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("5z3l: 3ndy rsala mn al32d... antbh 3la nfsk!", 3.5, 2)
  SoundRemoveAllQueuedSpeech(Az3l, true)
  Wait(3500)
  PedMoveToXYZ(Az3l, 2, -629, -280, 5)
  CameraReset()
  CameraReturnToPlayer()
  CameraSetWidescreen(true)
  Wait(500)
  PedsPrepareConversation(gPlayer, Saleh2, 4, 0)
  CameraSetFOV(65)
  Wait(2500)
  CameraSetFOV(40)
  Wait(1000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: Asm3... n8dr nstdrgh!!.. nrmy 3leh Be9'!!", 4, 2)
  SoundRemoveAllQueuedSpeech(Saleh2, true)
  PedDelete(Az3l)
  Wait(4000)
  PedSetActionNode(Saleh2, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Saleh: Okay jimmy.. we will", 3, 2)
  SoundRemoveAllQueuedSpeech(Saleh2, true)
  Wait(3000)
  PedSetActionNode(gPlayer, "/Global/6_02/FactionLeaderNIS/Preps/Chad01", "Act/Conv/6_02.act")
  TextPrintString("Jimmy: 5ly fz3tk ylho almdrseen!! yla t3al m3ay", 4, 2)
  SoundRemoveAllQueuedSpeech(Saleh2, true)
  PedDismissAllAllies(Saleh2)
  PedDismissAllAllies(ActorForS1)
  PedDismissAllAllies(ActorForS2)
  PedDismissAllAllies(Fz3a1)
  PedDismissAllAllies(Fz3a2)
  PedDismissAllAllies(Fz3a3)
  PedDismissAllAllies(Fz3a4)
  Wait(4000)
  CameraReset()
  CameraReturnToPlayer()
  CameraSetWidescreen(false)
  SoundSetAudioFocusPlayer()
  PlayerSetControl(1)
  PedMoveToXYZ(ActorForS1, 2, -648, -313, 0)
  PedMoveToXYZ(ActorForS2, 2, -651, -315, 0)
  PedMoveToXYZ(Fz3a1, 2, -648, -309, 0)
  PedMoveToXYZ(Fz3a2, 2, -604, -307, 0)
  PedMoveToXYZ(Fz3a3, 2, -606, -307, 0)
  PedMoveToXYZ(Fz3a4, 2, -608, -307, 0)
  EggsThrow()
end





function EggsThrow()
  AboJ3frBeforeBoss = PedCreateXYZ(65, -629, -280, 5)
  PedMoveToXYZ(AboJ3frBeforeBoss, 0, -583, -333, 5)
  PedSetWeapon(gPlayer, 312, 12)
  PedSetWeapon(Saleh2, 312, 10)
  TextPrintString("Throw The Eggs on ABO-J3FR!.. and drag him to the hole!", 5, 1)
  BlipAboJ3frBeforeBoss = AddBlipForChar(AboJ3frBeforeBoss, 0, 26, 4)
  repeat
    Wait(0)
  until PedGetLastHitWeapon(AboJ3frBeforeBoss) == 312
  PedDelete(ActorForS1)
  PedDelete(ActorForS2)
  PedDelete(Fz3a1)
  PedDelete(Fz3a2)
  PedDelete(Fz3a3)
  PedDelete(Fz3a4)
  BlipRemove(BlipAboJ3frBeforeBoss)
  BlipHole = BlipAddXYZ(-772, -134, 5, 0)
  PedSetPedToTypeAttitude(AboJ3frBeforeBoss, 13, 0)
  PedAttackPlayer(AboJ3frBeforeBoss, 3)
  TextPrintString("Now go to the hole!!!!..", 5, 1)
  PlayerSetPunishmentPoints(300)
  repeat
    Wait(0)
  until PedIsInAreaXYZ(gPlayer, -774, -59, 12, 8)
  PedDelete(Saleh2)
  BlipRemove(BlipHole)
  PlayerSetPunishmentPoints(0)
  CameraFade(2000, 0)
  CameraFade(1000, 1)
  PlayerSetControl(0)
  CameraSetWidescreen(true)
  PedMoveToXYZ(gPlayer, 2, -772, -134, 5)
  Wait(3500)
  CameraSetXYZ(-778, -89, 11)
  CameraLookAtXYZ(-772, -88, 7)
  ActorBossFightLead = PedCreateXYZ(65, -768, -62, 12)
  ActorBossFight1 = PedCreateXYZ(52, -767, -65, 12)
  ActorBossFight2 = PedCreateXYZ(51, -773, -59, 12)
  ActorBossFight3 = PedCreateXYZ(50, -769, -62, 12)
  PedSetInfiniteSprint(ActorBossFightLead, true)
  PedSetInfiniteSprint(ActorBossFight1, true)
  PedSetInfiniteSprint(ActorBossFight2, true)
  PedSetInfiniteSprint(ActorBossFight3, true)
  PedMoveToXYZ(ActorBossFightLead, 2, -772, -134, 5)
  PedMoveToXYZ(ActorBossFight1, 2, -772, -134, 5)
  PedMoveToXYZ(ActorBossFight2, 2, -772, -134, 5)
  PedMoveToXYZ(ActorBossFight3, 2, -772, -134, 5)
  Wait(7500)
  CameraFade(2000, 0)
  Wait(1000)
  CameraFade(1000, 1)
  CameraSetFOV(120)
  SoundPlayStream("MS_RussellInTheHole.rsm", 0.6)
  PedDelete(ActorBossFightLead)
  PedDelete(ActorBossFight1)
  PedDelete(ActorBossFight2)
  PedDelete(ActorBossFight3)
  AreaTransitionXYZ(8, -772, -134, 5)
  BossFightABOJ3FR = PedCreateXYZ(65, -771, -140, 5)
  PedShowHealthBar(BossFightABOJ3FR, true, "N_DrCrabblesnitch", true)
  GBossFight1 = PedCreateXYZ(52, -765, -133, 5)
  GBossFight2 = PedCreateXYZ(51, -778, -132, 5)
  GBossFight3 = PedCreateXYZ(50, -774, -140, 5)
  PedSetActionTree(BossFightABOJ3FR, "/Global/G_Striker_A", "Act/Anim/G_Striker_A.act")
  PedSetActionTree(GBossFight1, "/Global/G_Striker_A", "Act/Anim/G_Striker_A.act")
  PedSetActionTree(GBossFight2, "/Global/G_Striker_A", "Act/Anim/G_Striker_A.act")
  PedSetActionTree(GBossFight3, "/Global/G_Striker_A", "Act/Anim/G_Striker_A.act")
  TextPrintString("Beat ABO-J3FR!!", 4, 1)
  PlayerSetPunishmentPoints(100)
  PedSetMaxHealth(BossFightABOJ3FR, 1200)
  PedSetHealth(BossFightABOJ3FR, 1200)
  PedSetPedToTypeAttitude(BossFightABOJ3FR, 13, 0)
  PedAttackPlayer(BossFightABOJ3FR, 3)
  PedSetPedToTypeAttitude(GBossFight1, 13, 0)
  PedSetPedToTypeAttitude(GBossFight1, 5, 0)
  PedAttackPlayer(GBossFight1, 1)
  PedSetPedToTypeAttitude(GBossFight2, 13, 0)
  PedSetPedToTypeAttitude(GBossFight2, 5, 0)
  PedAttackPlayer(GBossFight2, 1)
  PedSetPedToTypeAttitude(GBossFight3, 13, 0)
  PedSetPedToTypeAttitude(GBossFight3, 5, 0)
  PedAttackPlayer(GBossFight3, 1)
  CameraReset()
  CameraReturnToPlayer()
  CameraSetWidescreen(false)
  PlayerSetControl(1)
  Wait(6000)
  SalehInBossFight = PedCreateXYZ(32, -768, -62, 12)
  Fz3aBossFight1 = PedCreateXYZ(33, -767, -65, 12)
  Fz3aBossFight2 = PedCreateXYZ(34, -773, -59, 12)
  Fz3aBossFight3 = PedCreateXYZ(35, -769, -62, 12)
  PedRecruitAlly(SalehInBossFight, Fz3aBossFight1)
  PedRecruitAlly(Fz3aBossFight1, Fz3aBossFight2)
  PedRecruitAlly(Fz3aBossFight2, Fz3aBossFight3)
  PedSetAllyAutoEngage(SalehInBossFight, true)
  PedSetAllyAutoEngage(Fz3aBossFight1, true)
  PedSetAllyAutoEngage(Fz3aBossFight2, true)
  PedSetAllyAutoEngage(Fz3aBossFight3, true)
  PedSetPedToTypeAttitude(SalehInBossFight, 0, 0)
  PedAttack(SalehInBossFight, GBossFight1, 3)
  PedSetPedToTypeAttitude(Fz3aBossFight1, 0, 0)
  PedAttack(Fz3aBossFight1, GBossFight2, 3)
  PedSetPedToTypeAttitude(Fz3aBossFight2, 0, 0)
  PedAttack(Fz3aBossFight2, GBossFight3, 3)
  PedSetPedToTypeAttitude(Fz3aBossFight3, 0, 0)
  PedAttack(Fz3aBossFight3, GBossFight3, 3)
  repeat
    if not PedIsDead(AboJ3frBossFightABOJ3FRFOffice) or PedIsValid(BossFightABOJ3FR) then
      Wait(2000)
      PedSetActionNode(BossFightABOJ3FR, "/Global/P_Bif/Offense/Short/Strikes/LightAttacks/JAB/Cross", "Act/anim/P_Bif.act")
      Wait(1000)
      PedSetActionNode(BossFightABOJ3FR, "/Global/BOSS_Darby/Offense/Short/Grapples/HeavyAttacks/Catch_Throw", "Act/anim/BOSS_Darby.act")
      Wait(1500)
      PedSetActionNode(BossFightABOJ3FR, "/Global/G_Striker_A/Offense/Short/Strikes/HeavyAttacks/HeavyKnee", "Act/anim/G_Striker_A.act")
      Wait(1000)
    end
    if PedIsDead(GBossFight1) and PedIsDead(GBossFight2) then
      PedAttack(SalehInBossFight, GBossFight3, 3)
    end
    if PedIsDead(GBossFight1) and PedIsDead(GBossFight3) then
      PedAttack(SalehInBossFight, GBossFight2, 3)
    end
    if PedIsDead(GBossFight2) and PedIsDead(GBossFight3) then
      PedAttack(SalehInBossFight, GBossFight1, 3)
    end
    if PedIsDead(GBossFight1) then
      PedAttack(SalehInBossFight, GBossFight2, 3)
    end
    if PedIsDead(GBossFight2) then
      PedAttack(Fz3aBossFight1, GBossFight1, 3)
    end
    if PedIsDead(GBossFight1) and PedIsDead(GBossFight2) then
      PedAttack(Fz3aBossFight1, GBossFight3, 3)
    end
    if PedIsDead(GBossFight1) and PedIsDead(GBossFight3) then
      PedAttack(Fz3aBossFight1, GBossFight2, 3)
    end
    if PedIsDead(GBossFight2) and PedIsDead(GBossFight3) then
      PedAttack(Fz3aBossFight1, GBossFight1, 3)
    end
    if PedIsDead(GBossFight3) then
      PedAttack(Fz3aBossFight2, GBossFight1, 3)
    end
    if PedIsDead(GBossFight1) and PedIsDead(GBossFight2) then
      PedAttack(Fz3aBossFight2, GBossFight3, 3)
    end
    if PedIsDead(GBossFight1) and PedIsDead(GBossFight3) then
      PedAttack(Fz3aBossFight2, GBossFight2, 3)
    end
    if PedIsDead(GBossFight2) and PedIsDead(GBossFight3) then
      PedAttack(Fz3aBossFight2, GBossFight1, 3)
    end
    if PedIsDead(GBossFight3) then
      PedAttack(Fz3aBossFight3, GBossFight1, 3)
    end
    if PedIsDead(GBossFight1) and PedIsDead(GBossFight2) then
      PedAttack(Fz3aBossFight3, GBossFight3, 3)
    end
    if PedIsDead(GBossFight1) and PedIsDead(GBossFight3) then
      PedAttack(Fz3aBossFight3, GBossFight2, 3)
    end
    if PedIsDead(GBossFight2) and PedIsDead(GBossFight3) then
      PedAttack(Fz3aBossFight3, GBossFight1, 3)
    end
    if PedIsDead(GBossFight1) and PedIsDead(GBossFight2) and PedIsDead(GBossFight3) then
      PedAttack(SalehInBossFight, BossFightABOJ3FR, 3)
      PedAttack(Fz3aBossFight1, BossFightABOJ3FR, 3)
      PedAttack(Fz3aBossFight2, BossFightABOJ3FR, 3)
      PedAttack(Fz3aBossFight3, BossFightABOJ3FR, 3)
    end
    Wait(0)
  until PedIsDead(BossFightABOJ3FR) or not PedIsValid(BossFightABOJ3FR)
  MissionSucceed()
end
